### ISSUE TITLE
Can you provide some example code?

### ISSUE THREAD

**Issue by Keltin42** [ChronSyn/react-native-keyevent-expo-config-plugin#3]
I was searching around looking for a way to detect keyboard presses (from a physical keyboard) in react native (without having a textinput), and I found this repository.  This looks kinda like what I'm looking for, but I'm not sure exactly how to use it from within my React Native Expo app.  Would you mind adding a quick sample to the README?

Additional question - I wanted to detect Right/Left Arrow clicks on the keyboard, but just taking a quick scan I'm guessing your implementation will over return A-Z?  Or I misunderstanding how it works?

**Comment by ChronSyn** [comment]
This is just a config plugin for the relevant library. You should direct any functionality questions there instead.
